  
  development:
    adapter: postgresql
    encoding: utf8
    database: rats_dev
    template: template0
    host: localhost
    port: 5432
    pool: 5
    username: jay
    password:

  test:
    adapter: postgresql
    encoding: utf8
    database: rats_test
    template: template0
    host: localhost
    port: 5432
    pool: 5
    username: jay
    password: 

  production:
    url:  <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 50 %>

